version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '22:00'
      timezone: 'Africa/Nairobi'
    open-pull-requests-limit: 99
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
    groups:
      fix-and-minor-updates:
        patterns:
          - '*'
        update-types:
          - 'minor'
          - 'patch'
